config/routes.rb
Rails.application.routes.draw do

  get 'items/index'

  root 'users#index'
  resources :orders
  resources :items
  resources :users, except: :destroy do
    member do 
      get 'toggle_suspension'
      post 'toggle_suspension'
      patch 'toggle_suspension'
      get 'topup' => "membership_cards#prepare_topup"
      post 'topup' => "membership_cards#topup"
      get 'pay' => "membership_cards#prepare_pay"
      post 'pay' => "membership_cards#pay"
    end

    resources :contacts, shallow: true
  end
  
  
  

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  belongs_to :store
  has_many :managed_store, class_name: "Store", foreign_key: "manager_id", dependent: :nullify

  has_one :membership_card, dependent: :destroy

  has_many :contacts
  has_many :card_statements, foreign_key: "user_id", 
                             dependent: :destroy
  has_many :operated_card_statements, class_name: "CardStatement", 
                                      foreign_key: "operator_id",
                              dependent: :destroy
  has_many :orders, inverse_of: :user
  has_many :user_coupons
  has_many :coupons, through: :user_coupons
  default_scope -> { order("suspended ASC, full_name DESC") }

  #validates :wechat_id, presence: true
  VALID_PHONE_NO_REGEX = /\A1[358]\d{9}\Z/i
  validates :phone_no, presence: true, 
                    length: {maximum: 11},
                    format: { with: VALID_PHONE_NO_REGEX },
                    uniqueness: true,
                    numericality: true
  validates :full_name, presence: true
  validates :status, presence: true
  validates :store_id, presence: true
  validates_inclusion_of :male, in: [true,false]


  accepts_nested_attributes_for :membership_card


  private 
    def twilio_client
      Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
    end

    def send_code
      twilio_client.messages.create(
        to: phone_no,
        from: ENV['TWILIO_PHONE_NUMBER'],
        body: "Your pin number is #{verification_code}, it will expire in one minute"
      )
    end

    def generate_code
      #if verification_code not yet set or time has expired
      if !self.verification_datetime || (Time.zone.now > self.verification_datetime)
        self.verification_code = rand(0000..9999).to_s.rjust(4, "0")
      end
      self.verification_datetime = Time.zone.now + 1.minute
      save
    end

    def verified?(entered_code)
      self.verification_code == entered_code && Time.zone.now < self.verification_datetime
    end

end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  include UsersHelper

  respond_to :html, :json

  def index
    @users, @users_count = get_paginated_users_and_count(params[:status],params[:page])

    respond_with(@users)
  end

  def show
    @user = User.find(params[:id])
    respond_with(@user)
  end

  def new
    @user = User.new
    @user.build_membership_card
  end

  def create
    @user = User.new(user_params)
    @user.membership_card.card_no = generate_card_no(@user.status)
    if @user.save
      #log_in @user
      flash.now[:notice] = "User was created successfully."
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.suspended
      flash.now[:warning] = "User cannot be modified"
    elsif @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def toggle_suspension
    @user = User.find(params[:id])
    if !@user.suspended
      @user.update(suspended:true,suspension_reason:params[:suspension_reason])
    else
      @user.update(suspended:false,suspension_reason:"")
    end

    @users,@users_count = get_paginated_users_and_count(params[:status],params[:page])

    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:full_name,:phone_no,:wechat_id,:status,:store_id,:male,
                                 membership_card_attributes: [:balance, :level_id])
  end

  def get_paginated_users_and_count(status,page)
    if status && status == "Staffs"
      @users_all = User.where("status == 'Admin' OR status == 'Manager' OR status == 'Staff'")
    else
      @users_all = User.where("status == 'Client'")
    end

    @users = @users_all.paginate(page: page)
    @users_count = @users_all.count

    return @users,@users_count
  end 

end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def generate_number(length)
    o = [('0'..'9')].map { |i| i.to_a }.flatten
    (0...length).map { o[rand(o.length)] }.join
  end 

  def generate_complex_code(length)
    o = [('0'..'9'),('a'..'z'),('A'..'Z')].map { |i| i.to_a }.flatten
    (0...length).map { o[rand(o.length)] }.join
  end 

  def generate_random_number(max_num)
    rand(max_num) + 1
  end

  def generate_card_no(status)
    code_length = 12
    if status == "Client"
      "4" + generate_number(code_length)
    elsif status == "Staff"
      "3" + generate_number(code_length)
    elsif status == "Manager"
      "2" + generate_number(code_length)
    elsif status == "Admin"
      "1" + generate_number(code_length)
    end
  end
end

app/views/users/_contact.html.erb
<%= contact.address %>
<%= link_to "编辑", edit_contact_path(contact) %>
<%= link_to "删除", contact_path(contact), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/users/_contacts.html.erb
<% @user.contacts.each do |contact| %>
  <div id="user-<%=@user.id%>-contact-<%=contact.id%>">
    <%= render 'contact', contact:contact %>
  </div>
  <br>
<% end %>

app/views/users/_user.html.erb
<%= link_to user.full_name + "," + user.phone_no + "," + user.status.first + "," + Level.find(user.membership_card.level_id).name, user_path(user) %>
<%= user.membership_card.balance %>
<%= link_to "充值", controller: "membership_cards", action: "prepare_topup", id: user.id %>
<%= link_to "扣款", controller: "membership_cards", action: "prepare_pay", id: user.id %>
<% if user.suspended %>
  <%= link_to "解冻账户", {controller: "users",
                          action: "toggle_suspension", 
                          id: user.id},
                          data: { confirm: "Are you sure?" },
                          remote: true,
                          :id => "suspend-" + user.id.to_s %>
<% else %>
  <% if user.status != "Admin" %>
    <%= link_to "修改", edit_user_path(user) %>
  <% end %>
  <%= link_to "冻结账户", "/", :id => "suspend-" + user.id.to_s %>
  <div class="hidden" id="suspend-<%= user.id %>-confirmation">
    <%= form_for(user, url: toggle_suspension_user_path(user), method: :post, remote: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.hidden_field :id, :value => user.id %>
      <%= f.label :suspension_reason, "冻结原因" %>
      <%= f.text_field :suspension_reason, class: 'form-control' %>
      <br>
      <%= f.submit "确认冻结", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/users/_user_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :full_name, "姓名", class: 'required' %>
<%= f.text_field :full_name, class: 'form-control' %>
<br>
<%= f.label :male, "称呼"%>
<%= f.radio_button :male, 1, checked: true, class: 'form-control' %>
<%= f.label :male, "先生", :value => true %>
<%= f.radio_button :male, 0,  class: 'form-control' %>
<%= f.label :male, "女士", :value => false %>
<br>
<%= f.label :phone_no, "电话号码", class: 'required'  %>
<%= f.text_field :phone_no, class: 'form-control' %>
<br>
<%= f.label :wechat_id, "微信号" %>
<%= f.text_field :wechat_id, class: 'form-control' %>
<br>
<%= f.label :status, "类别", class: 'required'  %>
<%= f.select :status, "<option>Client</option><option>Staff</option><option>Manager</option>".html_safe, class: 'form-control' %>
<br>
<%= f.label :store_id, "隶属店铺" %>
<%= f.select :store_id, Store.all.map{ |s| [s.name, s.id] }, class: 'form-control' %>
<br>
<%= f.fields_for :membership_card do |m| %>
<%= m.label :balance, "初始金额" %>
<%= m.text_field :balance, class: 'form-control' %>
<br>
<%= m.label :level_id, "会员卡等级" %>
<%= m.select :level_id, options_from_collection_for_select(Level.all, 'id', 'name'), class: 'form-control' %>
<br>
<% end %>

app/views/users/_users.html.erb
<% @users.each do |user| %>
  <div id="user-<%= user.id %>">
    <%= render 'user', user: user %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, '编辑用户') %>
<h1>编辑用户</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :full_name, "姓名" %>
      <%= f.text_field :full_name, class: 'form-control' %>
      <br>
      <%= f.label :phone_no, "电话号码" %>
      <%= f.text_field :phone_no, class: 'form-control' %>
      <br>
      <%= f.label :wechat_id, "微信号" %>
      <%= f.text_field :wechat_id, class: 'form-control' %>
      <br>
      <%= f.label :status, "类别" %>
      <%= f.select :status, options_for_select(["Client","Staff","Manager"],f.object.status), class: 'form-control' %>
      <br>
      <%= f.label :store_id, "隶属店铺" %>
      <%= f.select :store_id, Store.all.map{ |s| [s.name, s.id] }, class: 'form-control' %>
      <br>
      <%= fields_for f.object.membership_card do |m| %>
        <%= m.label :level_id, "会员卡等级" %>
        <%= m.select :level_id, options_from_collection_for_select(Level.all, 'id', 'name',m.object.level_id), class: 'form-control' %>
      <% end %>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "users#index") %>
<% if params["status"] %>
  <h1>当前只显示员工, 共有<%= @users_count%>名员工</h1>
<% else %>
  <h1>当前只显示客户， 共有<%= @users_count %>名客户</h1>
<% end %>
<%= link_to "只显示客户",users_path %>
<%= link_to "只显示员工",users_path(status:"Staffs") %>
<br>
<h2><%= link_to "添加新用户", new_user_path %></h2>
<%= will_paginate %>
<div id="users-div">
  <%= render 'users' %>
</div>

app/views/users/new.html.erb
<% provide(:title, '添加新用户') %>
<h1>添加新用户</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'user_fields', f:f %>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.full_name) %>
<%= @user.inspect %>
<br>
<%= @user.membership_card.inspect %>
<br>
<h2>常用地址列表</h2>
<div id="user-contacts">
  <%= render 'contacts', contacts:@user.contacts %>
</div>

<h3><%= link_to "添加常用地址", new_user_contact_path(@user) %></h3>
<h1><%= link_to "Back", users_path %></h1>

app/views/users/toggle_suspension.js.erb
$("div#users-div").html("<%= j (render 'users', users: @users) %>");
console.log("user.suspended: <%= @user.suspended %>");